/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.projeto.main.java.view;

import br.projeto.main.java.dao.DependenteDAO;
import br.projeto.main.java.dao.EmpregadoDAO;
import br.projeto.main.java.dao.EmpresaDAO;
import br.projeto.main.java.dao.LancamentoDAO;
import br.projeto.main.java.model.Dependente;
import br.projeto.main.java.model.Empregado;
import br.projeto.main.java.model.Empresa;
import br.projeto.main.java.model.Lancamento;
import br.projeto.main.java.util.FormatFactory;
import br.projeto.main.java.view.dependentes.viewDependente;
import br.projeto.main.java.view.usuario.ExcluirUsuarioView;
import br.projeto.main.java.view.empresa.viewEmpresa;
import br.projeto.main.java.view.folha.viewFolhaDePagamento;
import br.projeto.main.java.view.funcionario.viewFuncionario;
import br.projeto.main.java.view.lancamentos.viewLancamentos;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author marco
 */
public class viewPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form viewPrincipal
     */
    public viewPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        panelButtons = new javax.swing.JPanel();
        buttonEmpresa = new javax.swing.JButton();
        buttonFuncionario = new javax.swing.JButton();
        buttonLancamentos = new javax.swing.JButton();
        buttonSair = new javax.swing.JButton();
        buttonDependente = new javax.swing.JButton();
        btnGerarFolha = new javax.swing.JButton();
        jTButtonExcluirUsuario = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        acessoSuporte = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU PRINCIPAL");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                aoAbrirJanela(evt);
            }
        });

        panelButtons.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/empresaIcon.png"))); // NOI18N
        buttonEmpresa.setText("Empresa");
        buttonEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEmpresaActionPerformed(evt);
            }
        });

        buttonFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconFuncionario.png"))); // NOI18N
        buttonFuncionario.setText("Funcionario");
        buttonFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFuncionarioActionPerformed(evt);
            }
        });

        buttonLancamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconLancamento.png"))); // NOI18N
        buttonLancamentos.setText("Lançamentos");
        buttonLancamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLancamentosActionPerformed(evt);
            }
        });

        buttonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconeSair.png"))); // NOI18N
        buttonSair.setText("SAIR");
        buttonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSairActionPerformed(evt);
            }
        });

        buttonDependente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dependenteIcon.png"))); // NOI18N
        buttonDependente.setText("Dependentes");
        buttonDependente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDependenteActionPerformed(evt);
            }
        });

        btnGerarFolha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPagamento.png"))); // NOI18N
        btnGerarFolha.setText("Gerar Folha");
        btnGerarFolha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarFolhaActionPerformed(evt);
            }
        });

        jTButtonExcluirUsuario.setText("EXCLUIR USUARIO");
        jTButtonExcluirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTButtonExcluirUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelButtonsLayout = new javax.swing.GroupLayout(panelButtons);
        panelButtons.setLayout(panelButtonsLayout);
        panelButtonsLayout.setHorizontalGroup(
            panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTButtonExcluirUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGerarFolha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonDependente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonLancamentos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonFuncionario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonEmpresa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonSair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelButtonsLayout.setVerticalGroup(
            panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonEmpresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonFuncionario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonLancamentos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonDependente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGerarFolha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(jTButtonExcluirUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel13.setText("BEM VINDO !!!!");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("SISTEMA CONTABIL INICIADO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(218, Short.MAX_VALUE))
        );

        jMenu1.setText("Ajuda");

        acessoSuporte.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        acessoSuporte.setText("Suporte");
        acessoSuporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acessoSuporteActionPerformed(evt);
            }
        });
        jMenu1.add(acessoSuporte);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(panelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void aoAbrirJanela(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_aoAbrirJanela
        ViewLogin login = new ViewLogin(null, true);
        login.setVisible(true);
    }//GEN-LAST:event_aoAbrirJanela

    private void buttonEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEmpresaActionPerformed

        viewEmpresa ve = new viewEmpresa(null, false);

        try {

            ArrayList<Empresa> lista = new EmpresaDAO().buscarTodos();

            String[] columnNames = {"ID", "NOME", "RESPONSAVEL", "CPNJ"};
            DefaultTableModel dtm = new DefaultTableModel(columnNames, 0);

            for (Empresa em : lista) {
                Object[] values = {em.getId(), em.getNome(), em.getResponsavel(), em.getCnpj()};
                dtm.addRow(values);
            }

            ve.getjTableEmpresa().setModel(dtm);

            ve.setVisible(true);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro Driver não encontrado! ");
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Erro na consulta dos dadous ou conexão com banco");
        }
    }//GEN-LAST:event_buttonEmpresaActionPerformed

    private void buttonFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFuncionarioActionPerformed

        viewFuncionario vf = new viewFuncionario(null, false);

        try {

            ArrayList<Empregado> lista = new EmpregadoDAO().buscarTodos();

            Object[] columnNames = {"ID", "NOME EMPRESA", "NOME", "CPF", "SALARIO"};
            DefaultTableModel dtm = new DefaultTableModel(columnNames, 0);

            for (Empregado em : lista) {
                Object[] values = {em.getId(), em.getEmpresa().getNome(), em.getNome(), em.getCpf(), em.getSalarioBase()};
                dtm.addRow(values);
            }

            vf.getjTableFuncionario().setModel(dtm);

            vf.setVisible(true);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro Driver não encontrado! ");
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Erro na consulta dos dadous ou conexão com banco");
        }

    }//GEN-LAST:event_buttonFuncionarioActionPerformed

    private void buttonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_buttonSairActionPerformed

    private void buttonLancamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLancamentosActionPerformed

        viewLancamentos vl = new viewLancamentos(null, false);

        try {

            ArrayList<Lancamento> lista = new LancamentoDAO().buscarTodos();

            Object[] columnNames = {"ID", "NOME EMPRESA", "PATRIMONIO_TOTAL", "DEBITO", "CREDITO", "DESCRICAO"};
            DefaultTableModel dtm = new DefaultTableModel(columnNames, 0);

            for (Lancamento em : lista) {
                Object[] values = {em.getId(), em.getEmpresa().getNome(), "R$ "+em.getPatrimonioTotal(), "R$ "+em.getDebito(), "R$ "+em.getCredito(), em.getDescricao()};
                dtm.addRow(values);
            }

            vl.getjTableLancamento().setModel(dtm);

            vl.setVisible(true);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro Driver não encontrado! ");
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Erro na consulta dos dadous ou conexão com banco");
        }
    }//GEN-LAST:event_buttonLancamentosActionPerformed

    private void buttonDependenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDependenteActionPerformed

        viewDependente vd = new viewDependente(null, false);

        try {

            ArrayList<Dependente> lista = new DependenteDAO().buscarTodos();

            Object[] columnNames = {"ID", "EMPREGADO RESPONSAVEL", "NOME", "CPF"};
            DefaultTableModel dtm = new DefaultTableModel(columnNames, 0);

            for (Dependente em : lista) {
                Object[] values = {em.getId(), em.getResponsavel().getNome() + "",em.getNome() + "", em.getCpf()};
                dtm.addRow(values);
            }

            vd.getjTableDependente().setModel(dtm);

            vd.setVisible(true);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro Driver não encontrado! ");
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Erro na consulta dos dadous ou conexão com banco");
        }
    }//GEN-LAST:event_buttonDependenteActionPerformed

    private void acessoSuporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acessoSuporteActionPerformed
        JOptionPane.showMessageDialog(this, "ACESSE O SITE WWW.SISTEMACONTABIL.COM OU PARA A CENTRAL 0800985-695 PARA SUPORTE");
    }//GEN-LAST:event_acessoSuporteActionPerformed

    private void jTButtonExcluirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTButtonExcluirUsuarioActionPerformed
        ExcluirUsuarioView euw = new ExcluirUsuarioView(null, true);
        euw.setVisible(true);
    }//GEN-LAST:event_jTButtonExcluirUsuarioActionPerformed

    private void btnGerarFolhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarFolhaActionPerformed
       viewFolhaDePagamento vfdp = new viewFolhaDePagamento(null,true);
       
       vfdp.setVisible(true);
    }//GEN-LAST:event_btnGerarFolhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem acessoSuporte;
    private javax.swing.JButton btnGerarFolha;
    private javax.swing.JButton buttonDependente;
    private javax.swing.JButton buttonEmpresa;
    private javax.swing.JButton buttonFuncionario;
    private javax.swing.JButton buttonLancamentos;
    private javax.swing.JButton buttonSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jTButtonExcluirUsuario;
    private javax.swing.JPanel panelButtons;
    // End of variables declaration//GEN-END:variables
}
