/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.projeto.main.java.view.funcionario;

import br.projeto.main.java.dao.EmpregadoDAO;
import br.projeto.main.java.dao.EmpresaDAO;
import br.projeto.main.java.model.Empregado;
import br.projeto.main.java.model.Empresa;
import br.projeto.main.java.model.enumeration.SexoENUM;
import br.projeto.main.java.model.enumeration.situacaoAtualEmpregadoENUM;
import br.projeto.main.java.util.FormatFactory;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author marco
 */
public class viewCadastroFuncionario extends javax.swing.JDialog {

    /**
     * Creates new form viewCadastroFuncionario
     */
    public viewCadastroFuncionario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        JTFCodigo.setText("");
        JTFCodigo.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexo = new javax.swing.ButtonGroup();
        situacao = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTfInsertNomeFuncionario = new javax.swing.JTextField();
        jTfInsertEmpresaFunc = new javax.swing.JTextField();
        jTfInsertCpfFuncionario = new javax.swing.JTextField();
        jTfInsertNisFuncionario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTfInsertSalarioBase = new javax.swing.JTextField();
        radioBtnSexoFeminino = new javax.swing.JRadioButton();
        radioBtnSexoMasculino = new javax.swing.JRadioButton();
        radioInsertSituacaoAtivo = new javax.swing.JRadioButton();
        radioInsertSituacaoInativo = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        JTFCodigo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        radioButtonPlanoDeSaude = new javax.swing.JRadioButton();
        radioValeTransporte = new javax.swing.JRadioButton();
        radioValeAlimentacao = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jtfDataAdmissao = new javax.swing.JTextField();
        btnClean = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        JTFEndereco = new javax.swing.JTextField();
        radioBtnFalecido = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        JTFIdade = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        JTFDataNascimento = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CADASTRAR FUNCIONARIO");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconFuncionarioCadastro.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("NOME");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("CPF");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("NIS");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("CODIGO EMPRESA");

        jTfInsertNomeFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfInsertNomeFuncionarioActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("SALARIO BASE");

        jTfInsertSalarioBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfInsertSalarioBaseActionPerformed(evt);
            }
        });

        sexo.add(radioBtnSexoFeminino);
        radioBtnSexoFeminino.setText("FEMININO");
        radioBtnSexoFeminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnSexoFemininoActionPerformed(evt);
            }
        });

        sexo.add(radioBtnSexoMasculino);
        radioBtnSexoMasculino.setText("MASCULINO");
        radioBtnSexoMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnSexoMasculinoActionPerformed(evt);
            }
        });

        situacao.add(radioInsertSituacaoAtivo);
        radioInsertSituacaoAtivo.setText("ATIVO");

        situacao.add(radioInsertSituacaoInativo);
        radioInsertSituacaoInativo.setText("INATIVO");
        radioInsertSituacaoInativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioInsertSituacaoInativoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("SEXO");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("SITUAÇÃO");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("CODIGO");

        JTFCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFCodigoActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("BENEFÍCIOS");

        radioButtonPlanoDeSaude.setText("PLANO DE SAÚDE");

        radioValeTransporte.setText("VALE TRANSPORTE");
        radioValeTransporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioValeTransporteActionPerformed(evt);
            }
        });

        radioValeAlimentacao.setText("VALE ALIMENTAÇÃO");
        radioValeAlimentacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioValeAlimentacaoActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("DATA DE ADMISSÃO");

        btnClean.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconClear.png"))); // NOI18N
        btnClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPersist.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("ENDERECO");

        radioBtnFalecido.setText("FALECIDO");
        radioBtnFalecido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnFalecidoActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("IDADE");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("DATA DE NASCIMENTO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTfInsertCpfFuncionario))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTfInsertNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTfInsertEmpresaFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTfInsertNisFuncionario))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtfDataAdmissao))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTfInsertSalarioBase, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JTFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTFIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTFEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JTFDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel7))
                            .addComponent(radioBtnSexoFeminino, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioBtnSexoMasculino, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(9, 9, 9)
                                    .addComponent(jLabel8))
                                .addComponent(radioInsertSituacaoInativo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addComponent(radioInsertSituacaoAtivo)))
                            .addComponent(radioBtnFalecido))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel10))
                            .addComponent(radioValeTransporte)
                            .addComponent(radioButtonPlanoDeSaude)
                            .addComponent(radioValeAlimentacao))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClean, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jTfInsertNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTfInsertEmpresaFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTfInsertCpfFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jTfInsertNisFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTfInsertSalarioBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(JTFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(JTFIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jtfDataAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(JTFEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(JTFDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radioButtonPlanoDeSaude)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioValeTransporte))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radioInsertSituacaoAtivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioInsertSituacaoInativo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radioBtnSexoFeminino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioBtnSexoMasculino)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radioValeAlimentacao)
                            .addComponent(radioBtnFalecido)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnClean, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTfInsertNomeFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfInsertNomeFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfInsertNomeFuncionarioActionPerformed

    private void jTfInsertSalarioBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfInsertSalarioBaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfInsertSalarioBaseActionPerformed

    private void radioBtnSexoFemininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnSexoFemininoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBtnSexoFemininoActionPerformed

    private void radioBtnSexoMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnSexoMasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBtnSexoMasculinoActionPerformed

    private void radioInsertSituacaoInativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioInsertSituacaoInativoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioInsertSituacaoInativoActionPerformed

    private void JTFCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFCodigoActionPerformed

    private void radioValeTransporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioValeTransporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioValeTransporteActionPerformed

    private void radioValeAlimentacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioValeAlimentacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioValeAlimentacaoActionPerformed

    private void btnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanActionPerformed
        jTfInsertCpfFuncionario.setText("");
        jtfDataAdmissao.setText("");
        JTFCodigo.setText("");
        jTfInsertEmpresaFunc.setText("");
        jTfInsertNisFuncionario.setText("");
        jTfInsertNomeFuncionario.setText("");
        jTfInsertSalarioBase.setText("");
        radioBtnSexoFeminino.setSelected(false);
        radioBtnSexoMasculino.setSelected(false);
        radioButtonPlanoDeSaude.setSelected(false);
        radioInsertSituacaoAtivo.setSelected(false);
        radioInsertSituacaoInativo.setSelected(false);
        radioValeAlimentacao.setSelected(false);
        radioValeTransporte.setSelected(false);
        JTFDataNascimento.setText("");
        radioBtnSexoFeminino.setSelected(false);
        radioBtnSexoMasculino.setSelected(false);
        radioInsertSituacaoAtivo.setSelected(false);
        radioInsertSituacaoInativo.setSelected(false);
        JTFEndereco.setText("");
    }//GEN-LAST:event_btnCleanActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        Empregado emp = new Empregado();

        Empresa em = new Empresa();
        em.setId(Integer.parseInt(jTfInsertEmpresaFunc.getText()));

        emp.setCpf(String.valueOf(jTfInsertCpfFuncionario.getText()));
        emp.setDataDeAdmissao(FormatFactory.convertToDate(jtfDataAdmissao.getText()));
        emp.setEmpresa(em);
        emp.setNis(String.valueOf(jTfInsertNisFuncionario.getText()));
        emp.setPossuiPlanoDeSaude(radioButtonPlanoDeSaude.isSelected() == true);
        emp.setPossuiValeAlimentacao(radioValeAlimentacao.isSelected() == true);
        emp.setPossuiValeTransporte(radioValeTransporte.isSelected() == true);
        emp.setDataNascimento(FormatFactory.convertToDate(JTFDataNascimento.getText()));

        if (radioInsertSituacaoAtivo.isSelected() == true) {
            emp.setSituacao(situacaoAtualEmpregadoENUM.ATIVO);
        } else if (radioInsertSituacaoInativo.isSelected() == true) {
            emp.setSituacao(situacaoAtualEmpregadoENUM.INATIVO);
        } else {
            emp.setFalecido(true);
        }

        emp.setEndereco(JTFEndereco.getText());
        emp.setFalecido(radioBtnFalecido.isSelected() == true);
        emp.setIdade(Integer.parseInt(JTFIdade.getText()));
        emp.setNome(jTfInsertNomeFuncionario.getText());
        emp.setSalarioBase(Double.parseDouble(jTfInsertSalarioBase.getText()));

        if (radioBtnSexoFeminino.isSelected() == true) {
            emp.setSexo(SexoENUM.FEMININO);
        } else {
            emp.setSexo(SexoENUM.MASCULINO);
        }
        
        try {

            if (JTFCodigo.getText().isEmpty() == false) {
                emp.setId(Integer.parseInt(JTFCodigo.getText()));
                new EmpregadoDAO().alterar(emp);
            } else if (JTFCodigo.getText().isEmpty() == true) {
                new EmpregadoDAO().inserir(emp);
            }
            
            setVisible(false);

        } catch (SQLException ex) {
            JOptionPane.showConfirmDialog(null, "Erro Driver não encontrado !");
        } catch (ClassNotFoundException ex) {
            JOptionPane.showConfirmDialog(null, "Erro na conexão com o Bancou ou na inserção de dados.");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void radioBtnFalecidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnFalecidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBtnFalecidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                viewCadastroFuncionario dialog = new viewCadastroFuncionario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTFCodigo;
    private javax.swing.JTextField JTFDataNascimento;
    private javax.swing.JTextField JTFEndereco;
    private javax.swing.JTextField JTFIdade;
    private javax.swing.JButton btnClean;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTfInsertCpfFuncionario;
    private javax.swing.JTextField jTfInsertEmpresaFunc;
    private javax.swing.JTextField jTfInsertNisFuncionario;
    private javax.swing.JTextField jTfInsertNomeFuncionario;
    private javax.swing.JTextField jTfInsertSalarioBase;
    private javax.swing.JTextField jtfDataAdmissao;
    private javax.swing.JRadioButton radioBtnFalecido;
    private javax.swing.JRadioButton radioBtnSexoFeminino;
    private javax.swing.JRadioButton radioBtnSexoMasculino;
    private javax.swing.JRadioButton radioButtonPlanoDeSaude;
    private javax.swing.JRadioButton radioInsertSituacaoAtivo;
    private javax.swing.JRadioButton radioInsertSituacaoInativo;
    private javax.swing.JRadioButton radioValeAlimentacao;
    private javax.swing.JRadioButton radioValeTransporte;
    private javax.swing.ButtonGroup sexo;
    private javax.swing.ButtonGroup situacao;
    // End of variables declaration//GEN-END:variables

    void alterarRegistro(Empregado emp) {
        
        JTFCodigo.setText(String.valueOf(emp.getId()));
        JTFEndereco.setText(emp.getEndereco());
        JTFIdade.setText(String.valueOf(emp.getIdade()));
        jTfInsertCpfFuncionario.setText(emp.getCpf());
        jTfInsertNisFuncionario.setText(emp.getNis());
        jTfInsertSalarioBase.setText(String.valueOf(emp.getSalarioBase()));
        jTfInsertNomeFuncionario.setText(emp.getNome());
        
        if(emp.getSexo().equals(SexoENUM.FEMININO)){
            radioBtnSexoFeminino.setSelected(true);
        }else if(emp.getSexo().equals(SexoENUM.MASCULINO)){
            radioBtnSexoMasculino.setSelected(true);
        }
        
         if(emp.getSituacao().equals(situacaoAtualEmpregadoENUM.ATIVO)){
            radioInsertSituacaoAtivo.setSelected(true);
        }else if(emp.getSituacao().equals(situacaoAtualEmpregadoENUM.INATIVO)){
            radioInsertSituacaoInativo.setSelected(true);
        }
        
        radioButtonPlanoDeSaude.setSelected(emp.getPossuiPlanoDeSaude());
        radioValeAlimentacao.setSelected(emp.getPossuiValeAlimentacao());
        radioValeTransporte.setSelected(emp.getPossuiValeTransporte());
        radioBtnFalecido.setSelected(emp.isFalecido());
        
        JTFDataNascimento.setEnabled(false);
        jtfDataAdmissao.setEnabled(false);
        jTfInsertEmpresaFunc.setEnabled(false);
        
        JTFDataNascimento.setText(FormatFactory.formatDate(emp.getDataNascimento()));
        jTfInsertEmpresaFunc.setText(String.valueOf(emp.getEmpresa().getId()));
        jtfDataAdmissao.setText(FormatFactory.formatDate(emp.getDataDeAdmissao()));
       
        
    }

}
