/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.projeto.main.java.view.empresa;

import br.projeto.main.java.dao.EmpresaDAO;
import br.projeto.main.java.model.Empresa;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author marco
 */
public class viewEmpresa extends javax.swing.JDialog {

    /**
     * Creates new form viewEmpresa
     */
    public viewEmpresa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    viewEmpresa() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmpresa = new javax.swing.JTable();
        btnInsertEmpresa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jbtnAlterar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jbtnBuscarImpresa = new javax.swing.JButton();
        jTfSearchEmpresa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableEmpresa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableEmpresa);

        btnInsertEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconInsert.png"))); // NOI18N
        btnInsertEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertEmpresaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("EMPRESA");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconDelete.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jbtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconRefresh.png"))); // NOI18N
        jbtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAlterarActionPerformed(evt);
            }
        });

        jLabel2.setText("PESQUISAR NOME: ");

        jbtnBuscarImpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconSelect.png"))); // NOI18N
        jbtnBuscarImpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBuscarImpresaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jbtnAlterar)
                                .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(btnInsertEmpresa)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTfSearchEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jbtnBuscarImpresa)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTfSearchEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(jbtnBuscarImpresa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnInsertEmpresa)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnAlterar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertEmpresaActionPerformed

        try {
            viewCadastroEmpresa vce = new viewCadastroEmpresa(null, true);
            vce.setVisible(true);

            preencherGrid(new EmpresaDAO().buscarTodos());

        } catch (SQLException ex) {
            JOptionPane.showConfirmDialog(null, "Erro Driver não encontrado !");
        } catch (ClassNotFoundException ex) {
            JOptionPane.showConfirmDialog(null, "Erro na conexão com o Bancou ou na inserção de dados.");
        }

    }//GEN-LAST:event_btnInsertEmpresaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        final int tabela = jTableEmpresa.getSelectedRow();

        if (tabela < 0) {
            JOptionPane.showMessageDialog(null, "Selecione uma empresa!");
        } else {

            String nome = (String) jTableEmpresa.getValueAt(tabela, 1);
            int id = (int) jTableEmpresa.getValueAt(tabela, 0);

            if (JOptionPane.showConfirmDialog(null, "Deseja excluir cadastro da " + nome + "?") == JOptionPane.YES_OPTION) {

                try {

                    Empresa empresa = new Empresa();
                    empresa.setId(id);
                    new EmpresaDAO().apagar(empresa);
                    preencherGrid(new EmpresaDAO().buscarTodos());

                } catch (SQLException ex) {
                    JOptionPane.showConfirmDialog(null, "Erro Driver não encontrado !");
                } catch (ClassNotFoundException ex) {
                    JOptionPane.showConfirmDialog(null, "Erro na conexão com o Bancou ou na inserção de dados.");
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jbtnBuscarImpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBuscarImpresaActionPerformed

        try {
            ArrayList<Empresa> lista = new EmpresaDAO().buscarPeloNome(jTfSearchEmpresa.getText());
            preencherGrid(lista);

        } catch (SQLException ex) {
            JOptionPane.showConfirmDialog(null, "Erro Driver não encontrado !");
        } catch (ClassNotFoundException ex) {
            JOptionPane.showConfirmDialog(null, "Erro na conexão com o Bancou ou na inserção de dados.");
        }


    }//GEN-LAST:event_jbtnBuscarImpresaActionPerformed

    private void jbtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAlterarActionPerformed

        final int tabela = jTableEmpresa.getSelectedRow();

        if (tabela < 0) {
            JOptionPane.showMessageDialog(null, "Selecione uma empresa!");
        } else {
            int id = (int) jTableEmpresa.getValueAt(tabela, 0);

            try {
                
                Empresa emp = new EmpresaDAO().buscarPelaChave(id);
                
                viewCadastroEmpresa vce = new viewCadastroEmpresa(null, true);
                
                ArrayList<Empresa> lista = new EmpresaDAO().buscarTodos();
                
                vce.alterarRegistro(emp);
                
                vce.setVisible(true);
                
                preencherGrid(new EmpresaDAO().buscarTodos());

            } catch (SQLException ex) {
                JOptionPane.showConfirmDialog(null, "Erro Driver não encontrado !");
            } catch (ClassNotFoundException ex) {
                JOptionPane.showConfirmDialog(null, "Erro na conexão com o Bancou ou na inserção de dados.");
            }

        }
    }//GEN-LAST:event_jbtnAlterarActionPerformed

    public void preencherGrid(ArrayList<Empresa> lista) {

        String[] columnNames = {"ID", "NOME", "RESPONSAVEL", "CPNJ"};
        DefaultTableModel dtm = new DefaultTableModel(columnNames, 0);

        for (Empresa em : lista) {
            Object[] values = {em.getId(), em.getNome(), em.getResponsavel(), em.getCnpj()};
            dtm.addRow(values);
        }

        getjTableEmpresa().setModel(dtm);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                viewEmpresa dialog = new viewEmpresa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public JTable getjTableEmpresa() {
        return jTableEmpresa;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsertEmpresa;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEmpresa;
    private javax.swing.JTextField jTfSearchEmpresa;
    private javax.swing.JButton jbtnAlterar;
    private javax.swing.JButton jbtnBuscarImpresa;
    // End of variables declaration//GEN-END:variables
}
